"""
stock_list.py – Curated list of NSE stock symbols used by the AITrader scanner.

Symbols are in Yahoo Finance format (suffix ".NS") so they can be fetched with
yfinance in Paper mode.  The trading engine uses the bare symbol (without ".NS")
when routing to Shoonya in Live mode.

Extend NSE_SYMBOLS to include the full 1 500-stock universe as required.
"""

NSE_SYMBOLS: list[str] = [
    # NIFTY 50
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "KOTAKBANK.NS", "BHARTIARTL.NS", "ITC.NS", "SBIN.NS",
    "BAJFINANCE.NS", "LT.NS", "HCLTECH.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS",
    "NESTLEIND.NS", "POWERGRID.NS", "NTPC.NS", "ONGC.NS", "TECHM.NS",
    "TATAMOTORS.NS", "TATASTEEL.NS", "ADANIPORTS.NS", "JSWSTEEL.NS", "COALINDIA.NS",
    "M&M.NS", "BAJAJFINSV.NS", "DIVISLAB.NS", "DRREDDY.NS", "CIPLA.NS",
    "EICHERMOT.NS", "HEROMOTOCO.NS", "INDUSINDBK.NS", "BPCL.NS", "GRASIM.NS",
    "HDFCLIFE.NS", "SBILIFE.NS", "APOLLOHOSP.NS", "TATACONSUM.NS", "BAJAJ-AUTO.NS",
    "BRITANNIA.NS", "HINDALCO.NS", "UPL.NS", "SHREECEM.NS", "VEDL.NS",

    # NIFTY NEXT 50 (selection)
    "ADANIENT.NS", "ADANIGREEN.NS", "ADANITRANS.NS", "AMBUJACEM.NS", "AUROPHARMA.NS",
    "BANDHANBNK.NS", "BERGEPAINT.NS", "BIOCON.NS", "BOSCHLTD.NS", "CHOLAFIN.NS",
    "COLPAL.NS", "CONCOR.NS", "DABUR.NS", "DLF.NS", "GAIL.NS",
    "GODREJCP.NS", "HAVELLS.NS", "ICICIGI.NS", "ICICIPRULI.NS", "INDUSTOWER.NS",
    "INDIGO.NS", "IOC.NS", "IRCTC.NS", "JUBLFOOD.NS", "LICHSGFIN.NS",
    "LUPIN.NS", "MARICO.NS", "MCDOWELL-N.NS", "MUTHOOTFIN.NS", "NAUKRI.NS",
    "NMDC.NS", "PAGEIND.NS", "PETRONET.NS", "PIDILITIND.NS", "PNB.NS",
    "RECLTD.NS", "SIEMENS.NS", "SRF.NS", "TATACOMM.NS", "TORNTPHARM.NS",
    "TRENT.NS", "UNITDSPR.NS", "VOLTAS.NS", "WHIRLPOOL.NS", "ZOMATO.NS",

    # Mid-cap selection
    "ABCAPITAL.NS", "ALKEM.NS", "ATUL.NS", "BALKRISIND.NS", "BATAINDIA.NS",
    "CANBK.NS", "DEEPAKNTR.NS", "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS",
    "FORTIS.NS", "GLAXO.NS", "GMRINFRA.NS", "GRANULES.NS", "HAL.NS",
    "HINDPETRO.NS", "HONAUT.NS", "IDFCFIRSTB.NS", "IGL.NS", "INDIANB.NS",
    "INDHOTEL.NS", "JKCEMENT.NS", "JUBILANT.NS", "KAJARIACER.NS", "LAURUSLABS.NS",
    "LTTS.NS", "LALPATHLAB.NS", "MFSL.NS", "MINDTREE.NS", "MOTHERSUMI.NS",
    "MRF.NS", "MPHASIS.NS", "NAM-INDIA.NS", "NATIONALUM.NS", "NBCC.NS",
    "NLCINDIA.NS", "OBEROIRLTY.NS", "OFSS.NS", "PERSISTENT.NS", "PFC.NS",
    "RAIN.NS", "RAMCOCEM.NS", "SAIL.NS", "SOLARINDS.NS", "SONACOMS.NS",
    "STAR.NS", "SUPREMEIND.NS", "TATAELXSI.NS", "TORNTPOWER.NS", "ZEEL.NS",
]
